import MusicPlayer from "../src/components/MusicPlayer.vue";
import WeatherWidget from "../src/components/WeatherWidget.vue";
import CalendarWidget from "../src/components/Modules/CalendarWidget/CalendarWidget.vue";
import NewsWidget from "../src/components/NewsWidget.vue";
import YoutubeWidget from "../src/components/YoutubeWidget.vue";
import SpotifyPlayer from "../src/components/Modules/SpotifyPlayer/SpotifyPlayer.vue";
import StatsWidget from "../src/components/StatsWidget.vue";
import WaterWidget from "../src/components/WaterWidget.vue";
import SoccerTable from "../src/components/SoccerTable.vue";
import TimeWidget from "../src/components/TimeWidget.vue";
export { SpotifyPlayer, CalendarWidget };
